export const ROUTES = {
  HOME: "/",
  ABOUT_US: "/about-us",
  POLICY: "/policy",
  TERMS_OF_USE: "/terms",
  COOKIE_POLICY: "/cookie-policy",
  HOW_IT_WORKS: "/how",
  FAQ: "/faq",
  GUIDES: "/guides",
  HELP_CENTER: "/help-center",
  BLOGS: "/blogs",
  NEWS: "/news",
  TIPS: "/tips",
  TESTIMONIALS: "/testimonial",
  LOGIN: "/login",
  SIGN_UP: "/sign-up",
  VERIFY_EMAIL: (email: string) => `/verify-email/${encodeURIComponent(email)}`,
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: (email: string) =>
    `/reset-password/${encodeURIComponent(email)}`,
  CART: "/dashboard/cart",
  PUBLIC_USER_PROFILE: (id: string) => `/profile/about/${id}`,
  SET_TARGET: "/dashboard/service/set-up-target",
  TARGET: "/dashboard/report#target",
  MESSAGES: "/dashboard/message",
  USER_PROFILE: "/dashboard/profile",
  SUBSCRIPTION_PLANS: "/dashboard/subscription/plans",
  SUBSCRIPTION_OVERVIEW: "/dashboard/subscription/overview",
  REPORTS: "/dashboard/report",
  REPORT_INSIGHT: "/dashboard/report?r=Insights",
  WALLET: "/dashboard/wallet",
  TRANSACTIONS: "/dashboard/transactions",

  //material routes
  SEARCH_MATERIAL: "/catalog/materials",
  COMPARE_MATERIALS: "/material/compare",
  DASHBOARD_MATERIAL: `/dashboard/material`,
  DASHOBOARD_MY_MATERIALS: "/dashboard/material/my-listed-materials",
  LIST_NEW_MATERIAL: "/dashboard/material/list-new-material",
  DASHBOARD_SAVED_MATERIAL: "/dashboard/material/saved",
  GENERAL_MATERIAL_DETAILS: (id: string) => `/material/info/${id}`,
  USER_MATERIAL_DETAILS: (id: string) => `/dashboard/material/info/${id}`,
  EDIT_MATERIAL: (id: string) => `/dashboard/material/edit/${id}`,
  ALL_REVIEWS_FOR_MATERIAL: (id: string) => `/material/info/all-reviews/${id}`,

  //expert & business routes
  COMPARE_BUSINESSES: "/compare",
  HIRE_EXPERT: "/hire-experts",
  SEARCH_SERVICE: "/catalog/services",
  BUY_MATERIALS: "/buy-materials",
  PRIVATE_EXPERT: "/expert/private-expert",
  JOIN_EXPERT: "/expert/register",
  CONGRATULATIONS_BUSINESS_REGISTER: "/expert/register/congrats",
  EXPERT_REVIEWS: (id: string) => `/expert/reviews/${id}`,
  GENERAL_EXPERT_DETAILS: (id: string) => `/expert/info/${id}`,
  DASHBOARD_EXPERT: "/dashboard/expert",
  DASHBOARD_SERVICE_INFO: (id: string) => `/dashboard/service/info/${id}`,
  EXPERT_EDIT: (id: string) => `/dashboard/service/edit/${id}`,

  //jobs routes
  FIND_JOB: "/find-job",
  DASHBOARD_JOB: "/dashboard/job",
  DASHBOARD_LEAD: "/dashboard/lead",
  DASHBOARD_JOB_NEW: "/dashboard/job/new",
  DASHBOARD_JOB_LEAD: "/dashboard/job/lead",
  DASHBOARD_JOB_ACTIVE: "/dashboard/job/active",
  DASHBOARD_JOB_PAUSED: "/dashboard/job/paused",
  DASHBOARD_JOB_OVERDUE: "/dashboard/job/overdue",
  DASHBOARD_JOB_COMPLETED: "/dashboard/job/completed",
  DASHBOARD_USER_JOBS: "/dashboard/job/my-listed-jobs",
  DASHBOARD_APPLIED_JOBS: "/dashboard/job/application",
  DASHBOARD_SAVED_JOBS: "/dashboard/job/saved",
  GENERAL_BIDDABLE_JOB_DETAILS: (id: string) =>
    `/dashboard/job/info/biddable/${id}`,
  GENERAL_REGULAR_JOB_DETAILS: (id: string) =>
    `/dashboard/job/info/regular/${id}`,
  GENERAL_DIRECT_JOB_DETAILS: (id: string) =>
    `/dashboard/job/info/direct/${id}`,
  ACTIVE_BIDDABLE_JOB_INFO: (id: string) =>
    `/dashboard/job/active/info/biddable/${id}`,
  ACTIVE_REGULAR_JOB_INFO: (id: string) =>
    `/dashboard/job/active/info/regular/${id}`,
  ACTIVE_DIRECT_JOB_INFO: (id: string) =>
    `/dashboard/job/active/info/direct/${id}`,
  EDIT_BIDDABLE_JOB: (id: string) => `/dashboard/job/edit/biddable/${id}`,
  EDIT_REGULAR_JOB: (id: string) => `/dashboard/job/edit/regular/${id}`,
  EDIT_DIRECT_JOB: (id: string) => `/dashboard/job/edit/direct/${id}`,
  LIST_NEW_JOB: "/dashboard/job/list-new-job",
  LIST_DIRECT_JOB: "/dashboard/job/direct-contract",
  PLANNED_MAINTENANCE: "/dashboard/planned-maintenance",
  RECURRING_JOBS: "/dashboard/my-recurring-jobs",

  //prjects routes
  DASHBOARD_PROJECT_ACTIVE: "/dashboard/project/active",
  DASHBOARD_PROJECT_NEW: "/dashboard/project/new",
  DASHBOARD_PROJECT_OVERDUE: "/dashboard/project/overdue",
  DASHBOARD_PROJECT_PAUSED: "/dashboard/project/paused",
  DASHBOARD_PROJECT_COMPLETE: "/dashboard/project/completed",
  BIDDABLE_PROJECT_INFO: (id: string) =>
    `/dashboard/project/info/biddable/${id}`,
  REGULAR_PROJECT_INFO: (id: string) => `/dashboard/project/info/regular/${id}`,
  DIRECT_PROJECT_INFO: (id: string) => `/dashboard/project/info/direct/${id}`,
} as const;
